"""Manually curated research-content extractions for all 119 TRID records.
Each dict corresponds to records_clean.json by index.
Fields follow the agreed 17-column schema. 'Moderate' stance on ML_AI_Gap."""

EXTRACTIONS = [
# 0
{"Country":"Türkiye","City":"N/A (generic urban model)","Simulation_Type":"Monte Carlo","Software":"Not stated","Modeling_Method":"Stochastic break-even analysis over 10,000 simulated deliveries","Policy_Lever":"E-commerce returns / in-store pickup vs last-mile delivery","Freight_Segment":"Last-mile / e-commerce","Data_Source":"Real-world logistics data (distances, fuel rates, package counts)","Key_Finding":"In-store pickup is greener than courier delivery only above 24 packages/trip; drops to 17-20 when return emissions are allocated","Stated_Limitations":"Consumer behavior and low-emission mode uptake treated as exogenous","ML_AI_Gap":"Behavioral ML model of consumer choice between pickup and home delivery based on trip context; reinforcement learning for dynamic emission-aware channel steering","Geography_Bucket":"Europe (other)"},
# 1
{"Country":"Thailand","City":"Bangkok metropolitan area","Simulation_Type":"Monte Carlo","Software":"Not stated","Modeling_Method":"Total cost of ownership (TCO) simulation with stochastic fuel/resale prices","Policy_Lever":"BEV truck electrification and purchase subsidies","Freight_Segment":"Medium-duty urban freight","Data_Source":"Vehicle cost parameters, Thai market data","Key_Finding":"BEV trucks need ≥30% purchase subsidy or higher trip rate to beat ICEVs at 130-150 km/day","Stated_Limitations":"Charging station scarcity and charging time modeled as fixed constraints","ML_AI_Gap":"Learn battery degradation and charging demand curves from telematics; ML-optimized charger siting using demand forecasts","Geography_Bucket":"Asia"},
# 2
{"Country":"Italy","City":"Rome","Simulation_Type":"Monte Carlo + routing simulation","Software":"Not stated (custom AI routing + K-means)","Modeling_Method":"Monte Carlo cost analysis, AI-driven routing, K-means station placement","Policy_Lever":"Hydrogen cargo bikes for last-mile decarbonization","Freight_Segment":"Last-mile urban parcel","Data_Source":"Real logistics data from Rome","Key_Finding":"Hydrogen cargo bikes deliver 15% more parcels/day than e-bikes, cut refuelling detours by 31%, save up to 120 t CO2/yr per 100-bike fleet","Stated_Limitations":"Relies on assumed hydrogen pricing and infrastructure availability","ML_AI_Gap":"Demand-responsive dynamic routing via deep reinforcement learning; GNN-based refuelling station network optimization","Geography_Bucket":"Europe (EU)"},
# 3
{"Country":"USA","City":"Generic / California (Davis group)","Simulation_Type":"Simulation-optimization (Monte Carlo + metaheuristic)","Software":"Custom ALNS","Modeling_Method":"ME-C-LRP-TW multi-echelon location-routing, Monte Carlo + Adaptive Large Neighborhood Search","Policy_Lever":"Expedited-shipping last-mile strategy design (lockers, crowdsourcing, drones, robots, EVs)","Freight_Segment":"Last-mile e-commerce","Data_Source":"Synthetic dynamic-stochastic demand","Key_Finding":"Consolidation-based multi-echelon + EV fleets best balance sustainability; drones/robots viable for expedited under uncertainty","Stated_Limitations":"Uses synthetic demand; ALNS convergence sensitive to parameters","ML_AI_Gap":"Learn demand uncertainty distributions from historical orders; ML-guided neighborhood selection in ALNS (learning-to-search)","Geography_Bucket":"USA"},
# 4
{"Country":"Ukraine / Czech Republic / Brazil (multi-author)","City":"Medium-sized city (unspecified)","Simulation_Type":"Simulation + route optimization","Software":"Not stated","Modeling_Method":"Empirical data analysis + route optimization + simulation","Policy_Lever":"Electric cargo-bike program integrated with urban logistics hubs","Freight_Segment":"Last-mile parcel","Data_Source":"Empirical delivery-service data","Key_Finding":"E-cargo bikes integrated with logistics hubs enhance last-mile efficiency in medium cities","Stated_Limitations":"Generic framework; limited scenario coverage","ML_AI_Gap":"ML demand forecasting for hub placement; computer-vision load-factor monitoring","Geography_Bucket":"Europe (other)"},
# 5
{"Country":"India","City":"Kolkata (Bara Bazar area)","Simulation_Type":"Microsimulation + multi-objective optimization","Software":"NSGA-II","Modeling_Method":"Multi-objective optimization over simulated layby booking requests with spatial/temporal/duration deferment","Policy_Lever":"Loading-bay (layby) allocation policy","Freight_Segment":"Urban delivery (commercial stretch)","Data_Source":"Establishment-based freight surveys + operator interviews","Key_Finding":"Deferment strategies reduce fiscal losses, improve utilization, and lower unallocated-request rate","Stated_Limitations":"30 establishments / 10 bays scale; deferment cost structure from interviews","ML_AI_Gap":"Predict bay availability with ML using real-time IoT occupancy sensors; bandit algorithms for dynamic deferment assignment","Geography_Bucket":"Asia"},
# 6
{"Country":"China","City":"Not explicitly named (Chinese urban area)","Simulation_Type":"Air-dispersion + exposure simulation","Software":"Not stated","Modeling_Method":"Dispersion model + spatial econometric exposure model","Policy_Lever":"Truck emission exposure mitigation via emission standards, land use, traffic control","Freight_Segment":"Urban truck","Data_Source":"Mobile-phone signals + satellite images + traffic data","Key_Finding":"Freight demand, road network, residential/employment locations, commuting distance and age structure drive exposure disparities","Stated_Limitations":"Spatial econometric specification; single-city scope","ML_AI_Gap":"Graph neural nets for joint traffic-emission-exposure prediction; causal ML to disentangle policy effects on vulnerable subpopulations","Geography_Bucket":"Asia"},
# 7
{"Country":"USA","City":"New York State Capital Region","Simulation_Type":"Behavioral microsimulation","Software":"BMS (custom Behavioral Microsimulation Software)","Modeling_Method":"Agent-based tour generation with behavioral rules","Policy_Lever":"Distribution-center (DC) location policy — core vs outskirts","Freight_Segment":"Urban metropolitan distribution","Data_Source":"Not explicitly stated","Key_Finding":"DCs closer to urban core reduce total VMT vs outskirts DCs","Stated_Limitations":"Three scenarios only; behavioral rules may not generalize","ML_AI_Gap":"Learn tour-generation behavior from GPS data via inverse RL instead of hand-coded rules","Geography_Bucket":"USA"},
# 8
{"Country":"USA","City":"New York City","Simulation_Type":"Agent-based truck tour synthesis","Software":"Custom (benchmarked vs SimMobility, MASS-GT)","Modeling_Method":"Entropy-maximizing tour distribution from aggregate public data","Policy_Lever":"Truck capacity reduction policy (20% smaller trucks tested)","Freight_Segment":"Urban truck network (47 industries)","Data_Source":"NYC DOT data, Uber Movement speeds; aggregate public data","Key_Finding":"10.2% mean count error vs screenlines; 20%-smaller-truck policy cut ESALs by 49% but raised emissions 25%","Stated_Limitations":"Explicitly built because detailed establishment data not available","ML_AI_Gap":"ML-based tour synthesis from passive LBS/GPS data; transformer models for tour sequence generation","Geography_Bucket":"USA"},
# 9
{"Country":"Iran","City":"Not specified (national-scale)","Simulation_Type":"Agent-based microsimulation","Software":"Not stated","Modeling_Method":"Agent-based model with shippers, carriers, drivers as decision agents","Policy_Lever":"Trucking sector regulatory reform (market structure, branch requirements)","Freight_Segment":"Road freight trucking","Data_Source":"Calibration data (not detailed)","Key_Finding":"Competitive market replaces mandatory assignment → 6% cost reduction; relaxing branch rules → 20% market-share shift to top carriers","Stated_Limitations":"3.7% calibration error; behavior rules simplified","ML_AI_Gap":"RL agents learning carrier/driver strategies instead of hand-coded utility; causal policy-effect estimation","Geography_Bucket":"Middle East / Asia"},
# 10
{"Country":"Brazil","City":"Generic (developing-country urban area)","Simulation_Type":"Agent-based","Software":"Not stated","Modeling_Method":"ABM of last-mile delivery with failure and re-delivery attempts","Policy_Lever":"Delivery lockers (DLs) vs assisted home delivery, delivery-attempt policy","Freight_Segment":"Last-mile e-commerce","Data_Source":"84 scenario simulations","Key_Finding":"DLs + exclusion of 3-attempt policy raise net profit up to 79.1%","Stated_Limitations":"Profit model sensitive to cost assumptions","ML_AI_Gap":"ML to predict delivery-failure probability per household; optimize locker network siting via GNN","Geography_Bucket":"LATAM"},
# 11
{"Country":"Germany","City":"Karlsruhe","Simulation_Type":"Agent-based microsimulation","Software":"logiTopp","Modeling_Method":"ABM of CEPSP parcel volumes for companies","Policy_Lever":"Regional planning for parcel infrastructure under rising volumes","Freight_Segment":"CEP (courier express parcel), B2B","Data_Source":"OpenStreetMap + CEPSP expert interviews","Key_Finding":"Open-data-based modeling feasible; granularity limits remain","Stated_Limitations":"Reliance on open data restricts detail","ML_AI_Gap":"ML imputation of parcel demand from OSM + firmographic features; active learning to target interviews","Geography_Bucket":"Europe (EU)"},
# 12
{"Country":"Singapore","City":"Singapore","Simulation_Type":"Agent-based freight simulator","Software":"SimMobility Freight","Modeling_Method":"Screenline-based Two-step Calibration (SLTC) — demand adjustment + parameter update","Policy_Lever":"Calibration methodology (enabling policy analysis)","Freight_Segment":"Urban goods vehicle","Data_Source":"Screenline counts only","Key_Finding":"SLTC replicates observed counts with reasonable compute cost","Stated_Limitations":"Data scarcity for freight demand; calibration complexity","ML_AI_Gap":"Neural-network surrogate calibrators; Bayesian optimization to replace two-step heuristic","Geography_Bucket":"Asia"},
# 13
{"Country":"Denmark","City":"Not specified","Simulation_Type":"Hybrid simulation + optimization","Software":"Not stated","Modeling_Method":"Simulation + optimization algorithms + cost-effectiveness analysis","Policy_Lever":"Real-time disruption management (line-haul)","Freight_Segment":"Line-haul / inter-urban","Data_Source":"Real disruption scenario data","Key_Finding":"Re-planning strategies ranked by cost, reliability, CO2; DSS architecture proposed","Stated_Limitations":"Six fixed strategies tested","ML_AI_Gap":"Deep RL for real-time disruption response; predictive ML for weather-caused disruptions","Geography_Bucket":"Europe (EU)"},
# 14
{"Country":"Australia","City":"Melbourne CBD","Simulation_Type":"Simulation-optimization","Software":"Not stated (evolutionary algorithm + commercial re-optimization)","Modeling_Method":"Simulation-optimization with stochastic traffic, competition, illegal parking","Policy_Lever":"Loading-zone allocation and on-street parking management","Freight_Segment":"Last-mile delivery with walking","Data_Source":"Melbourne CBD network representation","Key_Finding":"Win-win parking configurations exist that satisfy couriers and city","Stated_Limitations":"Single CBD case; behavior of non-delivery drivers simplified","ML_AI_Gap":"ML-based illegal-parking prediction from camera feeds; multi-agent RL for adaptive zone allocation","Geography_Bucket":"Oceania"},
# 15
{"Country":"USA","City":"Seattle, Washington","Simulation_Type":"Discrete-event simulation + multi-objective optimization","Software":"Not stated","Modeling_Method":"DES with delivery arrivals; NSGA-2 and MOEA/D for optimization","Policy_Lever":"Building parking/loading resource allocation","Freight_Segment":"Last-50-ft / office-building delivery","Data_Source":"Real-world observations at downtown Seattle office","Key_Finding":"Optimal resource numbers balance worker-manager-planner costs; system overflows beyond 10-18 deliveries/hr","Stated_Limitations":"Single-building case","ML_AI_Gap":"CV-based automated delivery arrival detection; predictive ML for building-level parcel demand","Geography_Bucket":"USA"},
# 16
{"Country":"Netherlands","City":"National (applied to Dutch ZEZ cities)","Simulation_Type":"Multi-agent simulation","Software":"MASS-GT","Modeling_Method":"Empirical ABM with shipment and vehicle diaries","Policy_Lever":"Zero-emission zones (ZEZ)","Freight_Segment":"Urban goods","Data_Source":"Large automated TMS truck trip dataset","Key_Finding":"Framework validated for ZEZ analysis (details in companion papers)","Stated_Limitations":"TMS-based sample coverage","ML_AI_Gap":"ML-based vehicle-type imputation for non-reported trips; GNN shipment-size models","Geography_Bucket":"Europe (EU)"},
# 17
{"Country":"Singapore","City":"Singapore (commercial mall)","Simulation_Type":"Agent-based + demand/supply","Software":"Not stated","Modeling_Method":"Data-driven parking-choice model integrated with ABM","Policy_Lever":"Parking demand management for large urban freight generators (DMS)","Freight_Segment":"Delivery to malls / commercial complexes","Data_Source":"Parking choice dataset","Key_Finding":"DMS (pricing, centralized receiving, directed parking) improve travel time, emissions, queue length","Stated_Limitations":"Single case region","ML_AI_Gap":"Deep-learning parking-choice models with contextual features; RL for adaptive pricing","Geography_Bucket":"Asia"},
# 18
{"Country":"USA (prototypical N. American city)","City":"Prototypical","Simulation_Type":"Agent-based urban transportation simulation","Software":"SimMobility Freight","Modeling_Method":"Joint disaggregate behavioral models (expenditure, purchase amount, delivery mode, options)","Policy_Lever":"E-commerce delivery-option policy","Freight_Segment":"E-commerce / household","Data_Source":"Multiple sources for parameter specification","Key_Finding":"Framework can simulate e-commerce demand and policy impacts","Stated_Limitations":"Prototypical not real city; data sources disparate","ML_AI_Gap":"End-to-end neural choice models jointly predicting the four decisions; synthetic household generation via generative models","Geography_Bucket":"USA"},
# 19
{"Country":"Germany","City":"Berlin","Simulation_Type":"Multi-agent transport simulation","Software":"MATSim","Modeling_Method":"VRP-based synthetic tours + well-to-wheel + TCO","Policy_Lever":"Technology adoption: FCEV vs BEV vs ICEV for food retailing","Freight_Segment":"Food retailing distribution","Data_Source":"Public transport model for Berlin","Key_Finding":"BEV preferred economically/ecologically vs FCEV; FCEV only marginally better GHG today","Stated_Limitations":"Depends on electricity-mix assumptions","ML_AI_Gap":"Physics-informed neural nets for range prediction across vehicle types; scenario-generation ML for electricity-mix futures","Geography_Bucket":"Europe (EU)"},
# 20
{"Country":"South Africa","City":"Not specified","Simulation_Type":"Agent-based","Software":"Not stated","Modeling_Method":"ABM of carrier-receiver collaboration with cost sharing","Policy_Lever":"Freight carrier-receiver collaboration / cost-sharing scheme","Freight_Segment":"Urban freight","Data_Source":"Not specified","Key_Finding":"(Paper truncated in export — collaboration scheme explored)","Stated_Limitations":"Full text not in abstract","ML_AI_Gap":"Multi-agent RL to learn stable cost-sharing equilibria; game-theoretic ML for coalition formation","Geography_Bucket":"Africa"},
# 21
{"Country":"China","City":"Not specified","Simulation_Type":"System dynamics + evolutionary game","Software":"Not stated","Modeling_Method":"Evolutionary game model + system dynamics tripartite","Policy_Lever":"Crowd-logistics governance (penalties, profits, price regulation)","Freight_Segment":"Crowd-logistics","Data_Source":"Conceptual / simulated","Key_Finding":"Dynamic scenario outperforms static in restraining strategy fluctuation; profits drive driver participation","Stated_Limitations":"Conceptual, no empirical data","ML_AI_Gap":"Mean-field RL for large-population crowd-logistics dynamics; empirical ML grounding of utility parameters","Geography_Bucket":"Asia"},
# 22
{"Country":"Mexico","City":"Querétaro","Simulation_Type":"Microsimulation","Software":"Not stated","Modeling_Method":"Integrated methodology: freight-generation modeling + microsimulation scenarios","Policy_Lever":"Loading/unloading bay location, size, number","Freight_Segment":"Urban goods delivery","Data_Source":"Local traffic and establishment data","Key_Finding":"Methodology defines better bay infrastructure in congested medium city","Stated_Limitations":"Single-city case; aggregate approach","ML_AI_Gap":"ML land-use features for bay demand prediction; computer-vision bay-utilization monitoring","Geography_Bucket":"LATAM"},
# 23
{"Country":"USA","City":"Not specified (policy-level)","Simulation_Type":"Simulation modeling + case studies","Software":"Not stated","Modeling_Method":"Scenario case studies","Policy_Lever":"Zero-emission heavy-duty truck (ZEHDT) adoption — BEHDT vs hybrid","Freight_Segment":"Heavy-duty urban freight","Data_Source":"Case study data","Key_Finding":"BEHDT range-limited near-term; more viable by 2025-2030 with subsidies","Stated_Limitations":"High uncertainty in performance/price projections","ML_AI_Gap":"ML price-curve forecasting; RL for charging infrastructure rollout scheduling","Geography_Bucket":"USA"},
# 24
{"Country":"Netherlands","City":"Rotterdam (inner city)","Simulation_Type":"Agent-based","Software":"Not stated (city-logistics ABM)","Modeling_Method":"ABM with shippers, carriers, UCC operator","Policy_Lever":"Carbon credits + UCC subsidy (delivery cap & price DCAP)","Freight_Segment":"Urban goods delivery","Data_Source":"Stylized city model","Key_Finding":"DCAP + UCC subsidy financially viable and reduces externalities","Stated_Limitations":"Stylized, not full empirical","ML_AI_Gap":"RL design of carbon-credit market parameters; behavioral ML for shopkeeper UCC-acceptance","Geography_Bucket":"Europe (EU)"},
# 25
{"Country":"Germany","City":"Munich","Simulation_Type":"Agent-based","Software":"MITO-Freight / MATSim-style (from authors)","Modeling_Method":"Disaggregate ABM of commodity flows and parcel shipments","Policy_Lever":"Cargo-bike + van electrification for last-mile parcel","Freight_Segment":"Last-mile parcel","Data_Source":"Synthetic scenarios","Key_Finding":"Cargo bikes need van complement (large parcels); shift reduces CO2 but slightly ups total distance at low shares","Stated_Limitations":"Operating-time estimates simplified","ML_AI_Gap":"ML predict parcel dimensions/consolidation potential from order text; GNN micro-depot siting","Geography_Bucket":"Europe (EU)"},
# 26
{"Country":"Italy","City":"Not specified (European highway)","Simulation_Type":"Traffic microsimulation","Software":"Commercial (PTV Vissim or Aimsun, via Python script)","Modeling_Method":"Python script driving commercial sim to reproduce truck platooning","Policy_Lever":"Truck platooning strategies at highway on-ramps","Freight_Segment":"Long-haul truck","Data_Source":"Synthetic scenarios","Key_Finding":"Headway-adaptation strategy best balances platoon integrity and ramp merging","Stated_Limitations":"Single on-ramp geometry tested","ML_AI_Gap":"RL-controlled platoon maneuvers; computer-vision merging behavior model","Geography_Bucket":"Europe (EU)"},
# 27
{"Country":"South Africa","City":"Not specified","Simulation_Type":"Agent-based","Software":"MATSim","Modeling_Method":"ABM with vehicle-specific emissions concepts","Policy_Lever":"Low-emission zones (LEZ) access by vehicle emission class","Freight_Segment":"Urban goods / city logistics","Data_Source":"Not specified","Key_Finding":"Chosen model is sensitive to vehicle emission-concept assignment","Stated_Limitations":"Behavioral sensitivity needs empirical validation","ML_AI_Gap":"ML vehicle-class classification from license-plate/camera streams; sensitivity-quantification via SHAP on ABM","Geography_Bucket":"Africa"},
# 28
{"Country":"Greece","City":"Volos","Simulation_Type":"City-scale urban freight traffic microsimulation","Software":"Not stated","Modeling_Method":"Tailored evaluation framework + microsim","Policy_Lever":"Crowdshipping (car drivers / PT users as crowdshippers)","Freight_Segment":"Last-mile urban parcel","Data_Source":"Local case data from Volos","Key_Finding":"Crowdshipping mitigates last-mile impacts at sufficient adoption","Stated_Limitations":"Single mid-size city; adoption assumption external","ML_AI_Gap":"Matching-market ML (graph matching / bandit) for crowdshipper assignment; adoption-curve ML from behavioral surveys","Geography_Bucket":"Europe (EU)"},
# 29
{"Country":"Netherlands","City":"Rotterdam","Simulation_Type":"Multi-agent, empirical shipment-based tactical freight simulator","Software":"HARMONY Tactical Freight Simulator","Modeling_Method":"Long + short-term tactical choice simulation (channel, shipment size, vehicle, tour, delivery time)","Policy_Lever":"Zero-emission zones + UCCs at outskirt","Freight_Segment":"Urban goods + port-to-city","Data_Source":"Dutch tactical model","Key_Finding":"Emissions inside ZEZ drop ~90%; only ~10% city-wide; negligible regional; UCCs cause +0.25% VKT","Stated_Limitations":"Most emissions come from HGV not entering center","ML_AI_Gap":"ML vehicle-type-choice by logistic segment; spatial-ML regional spill-over estimation","Geography_Bucket":"Europe (EU)"},
# 30
{"Country":"Greece","City":"Volos","Simulation_Type":"Traffic microsimulation","Software":"Not stated","Modeling_Method":"Calibrated/validated traffic model with freight vehicles as PT-like routes","Policy_Lever":"Urban freight delivery validation framework","Freight_Segment":"Courier last-mile","Data_Source":"Volos taxi GPS + ELTA Courier data","Key_Finding":"Model simulates 199 delivery stops by 6 vehicles in case study","Stated_Limitations":"Small fleet sample","ML_AI_Gap":"ML-based calibration using richer passive GPS sources; auto-validation via count-station feeds","Geography_Bucket":"Europe (EU)"},
# 31
{"Country":"Greece","City":"Volos","Simulation_Type":"Traffic microsimulation","Software":"Not stated","Modeling_Method":"Impact assessment framework over calibrated microsim","Policy_Lever":"Urban freight transport impact assessment","Freight_Segment":"Courier last-mile","Data_Source":"Volos case data","Key_Finding":"22 kg CO2 and 84 h delay/day attributable to 6 freight vehicles","Stated_Limitations":"Small sample of freight vehicles","ML_AI_Gap":"ML upscaling from sample to fleet-level exposure; causal attribution ML","Geography_Bucket":"Europe (EU)"},
# 32
{"Country":"France","City":"Lyon","Simulation_Type":"Traffic-flow microsimulation + VRP","Software":"Not stated","Modeling_Method":"Realistic microsim producing time-dependent travel-time benchmarks at varying spatio-temporal granularity","Policy_Lever":"Spatio-temporal data granularity policy for routing","Freight_Segment":"Pickup-delivery / dial-a-ride","Data_Source":"Lyon traffic microsim","Key_Finding":"Granularity of traffic data materially affects routing solution quality","Stated_Limitations":"Benchmarks, not real operations","ML_AI_Gap":"ML travel-time prediction compressing sensor sparsity; surrogate travel-time maps via GNN for routing","Geography_Bucket":"Europe (EU)"},
# 33
{"Country":"Italy","City":"Not specified","Simulation_Type":"Microsimulation","Software":"Not stated","Modeling_Method":"Two routing algorithms + microsim for vehicle count and driver scheduling","Policy_Lever":"Automated van platooning with fixed split-up locations","Freight_Segment":"Urban distribution","Data_Source":"Methodological","Key_Finding":"Methodology designs platoon routes and driver schedules heuristically","Stated_Limitations":"No real-city case","ML_AI_Gap":"RL-driven platoon split-point selection under real traffic; ML fleet-size dimensioning","Geography_Bucket":"Europe (EU)"},
# 34
{"Country":"Singapore","City":"Singapore","Simulation_Type":"Agent-based urban freight simulator","Software":"SimMobility Freight","Modeling_Method":"Multi-scale disaggregate ABM (contracts, logistics, vehicle ops, parking)","Policy_Lever":"Delivery time-window regulations","Freight_Segment":"Urban freight","Data_Source":"Singapore data","Key_Finding":"Framework demonstrated for time-window policy evaluation","Stated_Limitations":"Illustrative demo only","ML_AI_Gap":"ML-based contract-choice models; simulation-budget allocation via Bayesian optimization","Geography_Bucket":"Asia"},
# 35
{"Country":"Netherlands (Western EU representative)","City":"Typical Western European city","Simulation_Type":"Agent-based","Software":"Custom ABM","Modeling_Method":"Markov decision process-based ABM","Policy_Lever":"Urban Consolidation Centers + access restrictions + subsidies","Freight_Segment":"Urban supply chain","Data_Source":"Aggregated literature data","Key_Finding":"Most schemes improve environment; UCC financial viability hard; backcast finds viable conditions","Stated_Limitations":"Aggregated data from literature","ML_AI_Gap":"Causal ML for intervention-combination effects; offline RL on historical city-policy outcomes","Geography_Bucket":"Europe (EU)"},
# 36
{"Country":"Singapore","City":"Singapore","Simulation_Type":"Discrete-event simulation + discrete-choice","Software":"Not stated","Modeling_Method":"Policy-sensitive parking choice model within DES","Policy_Lever":"Parking pricing and enforcement at large freight generators","Freight_Segment":"Commercial vehicle delivery to malls","Data_Source":"Real commercial-vehicle parking choice data (2 Singapore areas)","Key_Finding":"Model captures pricing/enforcement effects including illegal-parking attitudes","Stated_Limitations":"Two areas only","ML_AI_Gap":"Deep choice models with latent driver-attitude variables; camera-based violation data augmentation","Geography_Bucket":"Asia"},
# 37
{"Country":"UK","City":"West Midlands (Birmingham area)","Simulation_Type":"Discrete-event simulation","Software":"SIMUL8","Modeling_Method":"DES prototype of metro timetable","Policy_Lever":"Using metro infrastructure for urban freight","Freight_Segment":"Rail-based urban freight (exploratory)","Data_Source":"West Midlands Metro timetable","Key_Finding":"Metro underutilized → potential urban freight use on existing infrastructure","Stated_Limitations":"Feasibility study only","ML_AI_Gap":"ML passenger-demand forecasting to find freight-capacity windows; RL timetable co-optimization","Geography_Bucket":"Europe (other)"},
# 38
{"Country":"China","City":"Beijing","Simulation_Type":"System dynamics","Software":"Not stated","Modeling_Method":"System dynamics with 4 stakeholders, 8 scenarios 2007-2035","Policy_Lever":"Urban rail-based freight transit (URFT) investment, pricing, subsidies","Freight_Segment":"Rail-based urban freight","Data_Source":"Beijing historical data","Key_Finding":"Higher funding/capacity → larger reductions in congestion/pollution/accident losses","Stated_Limitations":"Scenario structure aggregated","ML_AI_Gap":"ML-calibrated SD parameters from operational data; causal ML for subsidy-effect estimation","Geography_Bucket":"Asia"},
# 39
{"Country":"Japan","City":"Tokyo Metropolitan Area","Simulation_Type":"Econometric simulation","Software":"Custom recursive-logit","Modeling_Method":"Recursive-logit travel choice model","Policy_Lever":"Time-dependent area charging in Tokyo center","Freight_Segment":"Urban freight truck tour","Data_Source":"GPS trajectories of trucks","Key_Finding":"Area charging alters truck travel patterns; RL-model parameters intuitive","Stated_Limitations":"Recursive logit specification","ML_AI_Gap":"Deep inverse-RL to learn choice utilities; graph-based tour embedding","Geography_Bucket":"Asia"},
# 40
{"Country":"Germany","City":"Berlin","Simulation_Type":"Multi-agent transport simulation","Software":"MATSim","Modeling_Method":"VRP + synthetic tours for BEV vs diesel food retailing","Policy_Lever":"Battery-electric truck adoption in food retailing","Freight_Segment":"Food retailing distribution","Data_Source":"Public Berlin transport model","Key_Finding":"56% tours achievable without recharge; 90% with 1 recharge; GHG −26 to −96%","Stated_Limitations":"Purchase-price sensitivity large","ML_AI_Gap":"Energy-consumption ML by tour context; RL for in-tour recharging decisions","Geography_Bucket":"Europe (EU)"},
# 41
{"Country":"Italy","City":"Veneto Region","Simulation_Type":"Aggregate tour simulation (OD)","Software":"Not stated","Modeling_Method":"Aggregate delivery-tour model analysis","Policy_Lever":"City-logistics scenario assessment enablement","Freight_Segment":"Commercial vehicle tours","Data_Source":"Floating car data (60 operating days)","Key_Finding":"Tour-pattern analysis highlights opportunities for model calibration","Stated_Limitations":"Aggregate approach","ML_AI_Gap":"FCD-driven tour pattern discovery via clustering/transformers","Geography_Bucket":"Europe (EU)"},
# 42
{"Country":"Germany","City":"Frankfurt","Simulation_Type":"Hybrid agent-based + discrete-event","Software":"Not stated","Modeling_Method":"Hybrid ABM/DES comparing urban logistics schemes","Policy_Lever":"Cargo-bike integration into urban consolidation","Freight_Segment":"Urban delivery","Data_Source":"Frankfurt case","Key_Finding":"Cargo bikes complement UCCs with environmental and financial benefits","Stated_Limitations":"Scheme comparison scope","ML_AI_Gap":"Hybrid-simulation surrogate modeling to accelerate scheme comparison; ML cost-prediction for schemes","Geography_Bucket":"Europe (EU)"},
# 43
{"Country":"Italy","City":"Rome","Simulation_Type":"Aggregate freight demand simulation","Software":"Not stated","Modeling_Method":"Multi-model system: wholesaler-retailer, retailer-consumer, wholesaler-consumer","Policy_Lever":"Fleet renewal + TDM + UCC + alt-fuel incentives (combined)","Freight_Segment":"City-logistics (all flows)","Data_Source":"Italian e-commerce/retail stats","Key_Finding":"Zero-CO2 goal 2030 out of reach; only combined policies yield major reductions","Stated_Limitations":"Aggregate approach","ML_AI_Gap":"Causal-ML for policy-combination effects; scenario-generation ML for e-commerce growth","Geography_Bucket":"Europe (EU)"},
# 44
{"Country":"Greece","City":"Not specified","Simulation_Type":"Simulation scheme","Software":"Not stated","Modeling_Method":"Experimental simulation model testing scheme scenarios","Policy_Lever":"Integrated urban freight scheme for GHG + traffic","Freight_Segment":"Urban + heavy commercial fleets","Data_Source":"Scenario data","Key_Finding":"Scheme competitive across scenarios","Stated_Limitations":"High-level scheme description","ML_AI_Gap":"ML emission estimation at route-level; RL routing within scheme","Geography_Bucket":"Europe (EU)"},
# 45
{"Country":"Japan","City":"Not specified (methodology)","Simulation_Type":"Multi-agent simulation + RL (ADP)","Software":"Custom","Modeling_Method":"MAS-ADP Reinforcement Learning for joint delivery","Policy_Lever":"UCC-based Joint Delivery System","Freight_Segment":"Urban freight","Data_Source":"Simulated","Key_Finding":"MAS-ADP beats MAS-Q-learning; better adaptation and emission reduction","Stated_Limitations":"Methodological paper","ML_AI_Gap":"Deep RL replacing ADP; multi-agent actor-critic for UCC coalition formation","Geography_Bucket":"Asia"},
# 46
{"Country":"Japan","City":"Tokyo Metropolitan Area","Simulation_Type":"Urban Logistics Land-use and Traffic Simulator","Software":"ULLTRA-SIM","Modeling_Method":"Simulation of logistics facility locations, chains, truck flow","Policy_Lever":"Logistics facility spatial distribution policy","Freight_Segment":"Urban logistics","Data_Source":"Tokyo data","Key_Finding":"Moderate concentration/deconcentration OK; scarcity near high demand worsens externalities","Stated_Limitations":"Depends on ULLTRA-SIM assumptions","ML_AI_Gap":"ML facility-siting with demand-heatmap learning; GNN for land-use-freight coupling","Geography_Bucket":"Asia"},
# 47
{"Country":"Japan","City":"Tokyo Metropolitan Area","Simulation_Type":"Agent-based urban freight simulator","Software":"SimMobility Freight","Modeling_Method":"Disaggregate commodity contract + shipment modeling","Policy_Lever":"Urban freight simulator enabling policy analysis","Freight_Segment":"Urban commodity flow","Data_Source":"2013 Tokyo Metropolitan Freight Survey","Key_Finding":"Good reproducibility at aggregate; agent-level challenging","Stated_Limitations":"Agent-level accuracy limited","ML_AI_Gap":"Generative ML for synthetic establishments; hierarchical-Bayes for agent-level uncertainty","Geography_Bucket":"Asia"},
# 48
{"Country":"Germany","City":"Berlin","Simulation_Type":"Agent-based freight traffic simulation","Software":"MATSim + jsprit","Modeling_Method":"VRP within ABM","Policy_Lever":"Tour planning / food-retail distribution policy","Freight_Segment":"Urban food distribution","Data_Source":"Berlin scenario","Key_Finding":"VRP within ABM feasible for urban food distribution","Stated_Limitations":"Scenario paper","ML_AI_Gap":"Learning-to-route neural solvers replacing VRP heuristics; demand-prediction ML feeding VRP","Geography_Bucket":"Europe (EU)"},
# 49
{"Country":"Poland + Norway","City":"Szczecin + Oslo","Simulation_Type":"Cellular automata","Software":"Custom","Modeling_Method":"CA simulation comparing with/without unloading bays","Policy_Lever":"Unloading bay provision","Freight_Segment":"Urban delivery","Data_Source":"Szczecin + Oslo traffic","Key_Finding":"Unloading bays cut congestion and emissions in both cities","Stated_Limitations":"CA abstraction","ML_AI_Gap":"Deep learning traffic state estimation to feed CA; CV-based bay demand sensing","Geography_Bucket":"Europe (other)"},
# 50
{"Country":"Italy","City":"Turin","Simulation_Type":"Simulation-optimization","Software":"Not stated","Modeling_Method":"Framework for building instances + assessing settings","Policy_Lever":"Multimodal last-mile delivery for e-commerce","Freight_Segment":"Last-mile e-commerce","Data_Source":"Torino case","Key_Finding":"Framework bridges data-scarcity gap in urban research","Stated_Limitations":"Framework paper","ML_AI_Gap":"ML-based instance generation from sparse real data; transfer learning across cities","Geography_Bucket":"Europe (EU)"},
# 51
{"Country":"Japan","City":"Tokyo Metropolitan Area","Simulation_Type":"Agent-based (within SimMobility Freight)","Software":"SimMobility Freight","Modeling_Method":"Error-component logit mixture nested supplier selection","Policy_Lever":"Commodity flow channel/supplier policy","Freight_Segment":"Metropolitan commodity flow","Data_Source":"Tokyo Metropolitan Freight Survey","Key_Finding":"Captures distribution-channel effects on supplier choice","Stated_Limitations":"Data-dependent","ML_AI_Gap":"Deep choice models capturing supplier-chain networks; GNN for supplier-receiver relationships","Geography_Bucket":"Asia"},
# 52
{"Country":"France","City":"Various French cities","Simulation_Type":"Urban freight simulation (FRETURB)","Software":"FRETURB","Modeling_Method":"Establishment-based urban freight simulation","Policy_Lever":"Governance / urban freight policy","Freight_Segment":"Urban goods","Data_Source":"French freight surveys (20+ years)","Key_Finding":"FRETURB robust 20 years after calibration with marginal updates","Stated_Limitations":"Needs periodic organisational updates","ML_AI_Gap":"Online ML for model updating from streaming data","Geography_Bucket":"Europe (EU)"},
# 53
{"Country":"Italy","City":"N/A (literature review)","Simulation_Type":"Literature review of ABS","Software":"N/A","Modeling_Method":"Classification review","Policy_Lever":"City logistics (general)","Freight_Segment":"Urban goods","Data_Source":"Literature","Key_Finding":"ABS suitable but applications are test-case / small area","Stated_Limitations":"Review","ML_AI_Gap":"Meta-learning across ABS studies; benchmark datasets with ML baselines","Geography_Bucket":"Europe (EU)"},
# 54
{"Country":"USA","City":"North Dakota","Simulation_Type":"Agent-based microsimulation","Software":"Not stated","Modeling_Method":"Multimodal ABM of agricultural/grain flow","Policy_Lever":"Rural/non-urban freight policy (truck weight restrictions)","Freight_Segment":"Rural agricultural freight","Data_Source":"North Dakota grain industry data","Key_Finding":"Microscopic ABM can model grain production-consumption flows","Stated_Limitations":"Domain-specific (grain)","ML_AI_Gap":"Commodity-price-responsive ML for agricultural flow prediction","Geography_Bucket":"USA"},
# 55
{"Country":"USA","City":"Maricopa region (Phoenix metro)","Simulation_Type":"Microsimulation-based megaregion freight model","Software":"Custom (SHRP2 C20)","Modeling_Method":"Firm synthesis + supply chain + mode/path + truck tour","Policy_Lever":"Megaregion freight forecasting","Freight_Segment":"Megaregion freight","Data_Source":"Integrated commercial + public datasets","Key_Finding":"Systematic data-integration framework for megaregion","Stated_Limitations":"Data gaps noted","ML_AI_Gap":"ML data fusion across sources; entity-resolution ML for firm synthesis","Geography_Bucket":"USA"},
# 56
{"Country":"Italy","City":"Rome (city center)","Simulation_Type":"Vehicle energy microsimulation","Software":"VT-CPEM adapted","Modeling_Method":"Physics-based energy consumption model","Policy_Lever":"Electric Fuel Vehicle (EFV) operations in LTZ","Freight_Segment":"Urban pickup/delivery","Data_Source":"Real EFV data from Rome logistics company","Key_Finding":"Truck weight, max speed, decelerations drive EFV energy consumption","Stated_Limitations":"Single operator dataset","ML_AI_Gap":"Neural-network energy model beating physics baseline; anomaly detection for battery faults","Geography_Bucket":"Europe (EU)"},
# 57
{"Country":"Japan","City":"Not specified (methodology)","Simulation_Type":"Multi-agent simulation + ADP RL","Software":"Custom","Modeling_Method":"MAS-ADP for carrier and UCC operator","Policy_Lever":"Urban Consolidation Centers","Freight_Segment":"City logistics","Data_Source":"Simulated","Key_Finding":"UCC reduces cost 8%, emissions 36%; ADP beats Q-learning","Stated_Limitations":"Methodological","ML_AI_Gap":"Deep RL (PPO/SAC) replacing ADP; multi-agent RL for coalition UCC operation","Geography_Bucket":"Asia"},
# 58
{"Country":"Germany","City":"Berlin","Simulation_Type":"Simulation (agent-based / city-scale)","Software":"Not stated","Modeling_Method":"Case studies of cargo-bike + pickup-point","Policy_Lever":"Cargo-bike last-mile + pickup points","Freight_Segment":"Urban parcel last-mile","Data_Source":"Berlin spatial/temporal structure","Key_Finding":"Cargo bikes cost-effective and greener; pickup-point benefits offset by consumer trips","Stated_Limitations":"Two measures tested","ML_AI_Gap":"Consumer pickup-trip ML prediction; RL dynamic pickup-point activation","Geography_Bucket":"Europe (EU)"},
# 59
{"Country":"USA","City":"Florida (state-level corridors)","Simulation_Type":"Traffic microsimulation","Software":"VISSIM + GIS","Modeling_Method":"General linear model over VISSIM scenarios + GIS heatmaps","Policy_Lever":"Exclusive Truck Platooning Lane (ETPL) on SIS corridors","Freight_Segment":"Long-haul truck on limited-access highway","Data_Source":"FL SIS corridor data","Key_Finding":"ETPL reduces truck travel time without hurting cars on most corridors","Stated_Limitations":"Scenario-based","ML_AI_Gap":"RL dynamic lane-management; ML truck-percentage forecasting by corridor","Geography_Bucket":"USA"},
# 60
{"Country":"Japan","City":"Tokyo Metropolitan Area","Simulation_Type":"Agent-based (nested logit model)","Software":"SimMobility Freight","Modeling_Method":"Nested logit for supplier function + supplier choice","Policy_Lever":"Distribution channel modeling for freight flows","Freight_Segment":"Urban commodity","Data_Source":"Tokyo Metropolitan Freight Survey","Key_Finding":"Logistics chain structure matters for flow modeling","Stated_Limitations":"Household/light manufacturing only","ML_AI_Gap":"Neural nested logit; graph-based supplier-receiver embedding","Geography_Bucket":"Asia"},
# 61
{"Country":"Germany","City":"Berlin","Simulation_Type":"Microsimulation","Software":"Not stated","Modeling_Method":"Two case-study microsim (cargo bike + pickup point)","Policy_Lever":"Cargo-bike + pickup-point","Freight_Segment":"Last-mile parcel","Data_Source":"Berlin case","Key_Finding":"Cargo bikes beneficial; pickup-point gains offset by consumer trips","Stated_Limitations":"Net-effect claim needs large-scale validation","ML_AI_Gap":"Counterfactual ML for net-effect estimation at scale","Geography_Bucket":"Europe (EU)"},
# 62
{"Country":"Netherlands","City":"Rotterdam agglomeration","Simulation_Type":"Agent-based","Software":"MASS-GT","Modeling_Method":"Data-driven ABM baseline","Policy_Lever":"Urban freight sustainability framework","Freight_Segment":"Urban goods","Data_Source":"Dutch TMS dataset","Key_Finding":"Baseline prototype simulates all urban freight patterns","Stated_Limitations":"No behavioral logit yet","ML_AI_Gap":"Deep-learning logistic-decision modules; active learning for missing data","Geography_Bucket":"Europe (EU)"},
# 63
{"Country":"USA","City":"Not specified (urban test network)","Simulation_Type":"Semi-analytic traffic simulation","Software":"Custom Lax-Hopf","Modeling_Method":"LWR-based fast algorithm for multiple moving bottlenecks","Policy_Lever":"Traffic-management for truck/bus impacts","Freight_Segment":"Urban trucks + buses","Data_Source":"Synthetic network","Key_Finding":"Semi-analytic scheme efficient for real-time truck/bus bottleneck analysis","Stated_Limitations":"LWR assumptions","ML_AI_Gap":"Neural PDE surrogates for LWR; ML arrival-time prediction of moving bottlenecks","Geography_Bucket":"USA"},
# 64
{"Country":"Italy","City":"Catania / generic Italian","Simulation_Type":"ABM + discrete choice","Software":"Not stated","Modeling_Method":"DCM + ABM integrated for stakeholder policy acceptance","Policy_Lever":"Stakeholder-engaged UFT policy-making","Freight_Segment":"Urban freight","Data_Source":"Stakeholder survey","Key_Finding":"Framework ranks acceptable policies accounting for interactions","Stated_Limitations":"Feasibility demonstration","ML_AI_Gap":"Opinion-dynamics ML (GNN) for preference propagation; LLM-based stakeholder interaction simulation","Geography_Bucket":"Europe (EU)"},
# 65
{"Country":"Italy","City":"Rome (LTZ)","Simulation_Type":"Agent-based + discrete choice","Software":"Custom","Modeling_Method":"Multilayer network + opinion dynamics + DCM + ABM","Policy_Lever":"Participatory decision-making on UFT policy","Freight_Segment":"Urban freight","Data_Source":"Rome LTZ stakeholder data","Key_Finding":"Ranks policies that max consensus and min utility loss","Stated_Limitations":"Requires stakeholder input","ML_AI_Gap":"GNN opinion dynamics; active learning on stakeholder preferences","Geography_Bucket":"Europe (EU)"},
# 66
{"Country":"Poland","City":"Not specified","Simulation_Type":"Cellular automata","Software":"Custom","Modeling_Method":"CA simulation of loading/unloading bay use","Policy_Lever":"Loading/unloading bay provision","Freight_Segment":"Urban freight","Data_Source":"Conceptual","Key_Finding":"CA useful for bay-efficiency analysis","Stated_Limitations":"Abstract model","ML_AI_Gap":"Learn CA rules from real traffic video; RL adaptive bay reservation","Geography_Bucket":"Europe (other)"},
# 67
{"Country":"Brazil","City":"Belo Horizonte","Simulation_Type":"Multi-agent","Software":"Not stated","Modeling_Method":"Multi-agent model with stakeholder relationships","Policy_Lever":"Flood/disaster response for urban freight","Freight_Segment":"Urban goods under disruption","Data_Source":"Belo Horizonte case","Key_Finding":"Multi-agent analysis quantifies flood impacts and mitigation","Stated_Limitations":"Exploratory","ML_AI_Gap":"ML flood-impact forecasting; RL contingency routing under disruption","Geography_Bucket":"LATAM"},
# 68
{"Country":"Germany","City":"Not specified","Simulation_Type":"System dynamics","Software":"Not stated","Modeling_Method":"Causal-loop diagram → quantitative SD","Policy_Lever":"Urban freight long-term forecasting","Freight_Segment":"Urban freight (general)","Data_Source":"Conceptual","Key_Finding":"Qualitative causal loops set up for quantitative SD","Stated_Limitations":"Early-stage qualitative","ML_AI_Gap":"ML to estimate SD parameters from time-series; causal discovery for loop validation","Geography_Bucket":"Europe (EU)"},
# 69
{"Country":"USA","City":"Not specified (small city)","Simulation_Type":"Activity-based transportation simulation","Software":"TRANSIMS","Modeling_Method":"Logistic regression + TRANSIMS simulation","Policy_Lever":"Crowdsourcing last-mile via retail social networks","Freight_Segment":"Last-mile parcel","Data_Source":"101-person survey + real-city activity data","Key_Finding":"−57% truck miles; −$8600/day; −55% NOx/PM","Stated_Limitations":"Small survey; crowdshipper-willingness assumed","ML_AI_Gap":"GNN over social network for match prediction; ML willingness-to-deliver prediction","Geography_Bucket":"USA"},
# 70
{"Country":"Singapore","City":"Singapore","Simulation_Type":"Data-driven simulation with parking-choice model","Software":"Not stated","Modeling_Method":"Simple parking-choice model + sim of mall arrivals","Policy_Lever":"Centralized goods receiving stations (CR) at malls","Freight_Segment":"Mall delivery","Data_Source":"Video + image recognition at a Singapore mall","Key_Finding":"Counterintuitive: CR may increase queue delay unless handling <15 min","Stated_Limitations":"Single mall","ML_AI_Gap":"CV-based delivery-flow monitoring; RL adaptive handling-time caps","Geography_Bucket":"Asia"},
# 71
{"Country":"USA","City":"Georgia (small urban + rural corridors)","Simulation_Type":"Ambient air-quality simulation","Software":"Not stated","Modeling_Method":"Multi-step pollution + health risk model","Policy_Lever":"Air quality / environmental justice along freight corridors","Freight_Segment":"Corridor trucks","Data_Source":"Georgia freight corridors 2007/2040","Key_Finding":"Rural freight emissions grow by 2040; minority/low-income bear disproportionate exposure","Stated_Limitations":"Forecast assumptions","ML_AI_Gap":"ML downscaling of pollution to community level; causal ML for env-justice attribution","Geography_Bucket":"USA"},
# 72
{"Country":"Greece","City":"N/A (literature/roadmap)","Simulation_Type":"Review of smart logistics simulation","Software":"N/A","Modeling_Method":"Roadmap of simulation techniques","Policy_Lever":"Smart urban distribution (general)","Freight_Segment":"Urban freight","Data_Source":"Literature","Key_Finding":"State-of-practice mapping","Stated_Limitations":"Review","ML_AI_Gap":"ML-augmented smart logistics (e.g., digital-twin + ML)","Geography_Bucket":"Europe (EU)"},
# 73
{"Country":"UK","City":"Not specified (large establishment)","Simulation_Type":"Microsimulation","Software":"Not stated","Modeling_Method":"Microsim at establishment level","Policy_Lever":"Establishment-level traffic management","Freight_Segment":"Establishment freight","Data_Source":"Abstract truncated","Key_Finding":"Abstract not available in export","Stated_Limitations":"Abstract missing","ML_AI_Gap":"ML establishment-demand prediction; CV-based gate-activity monitoring","Geography_Bucket":"Europe (other)"},
# 74
{"Country":"USA","City":"New York City (8th Ave)","Simulation_Type":"Traffic microsimulation","Software":"Not stated","Modeling_Method":"HCM2010 vs kinematic-wave analytical model + microsim","Policy_Lever":"Signal timing under freight lane-blockage","Freight_Segment":"Urban signalized arterial","Data_Source":"6-hour observation on 8th Ave NYC","Key_Finding":"Kinematic-wave model captures delivery-location effects that HCM coarse method misses","Stated_Limitations":"Single corridor","ML_AI_Gap":"Neural queueing models; CV delivery-event detection to feed signal controllers","Geography_Bucket":"USA"},
# 75
{"Country":"Poland","City":"Szczecin","Simulation_Type":"Pollution dispersion simulation","Software":"Not stated","Modeling_Method":"Line-source emission model","Policy_Lever":"Air-quality impact of freight","Freight_Segment":"Urban freight emissions","Data_Source":"Szczecin traffic surveys + detectors","Key_Finding":"Model identifies pollution hotspots at junctions","Stated_Limitations":"Straight-section + junction only","ML_AI_Gap":"Deep-learning dispersion surrogate; sensor-fusion real-time AQ estimation","Geography_Bucket":"Europe (other)"},
# 76
{"Country":"Netherlands","City":"N/A (methodology)","Simulation_Type":"Participatory simulation gaming + ABM","Software":"Custom game","Modeling_Method":"ABM validation via gaming with human players","Policy_Lever":"ABM validation methodology","Freight_Segment":"City logistics","Data_Source":"Game experiments","Key_Finding":"Participatory gaming promising for ABM agent validation","Stated_Limitations":"Proof of concept","ML_AI_Gap":"LLM-based digital stakeholders for ABM validation; learning-from-human-play ML","Geography_Bucket":"Europe (EU)"},
# 77
{"Country":"Austria","City":"Vienna","Simulation_Type":"Vehicle/system multiphysical simulation","Software":"Not stated","Modeling_Method":"Toyota hybrid model + operational strategy validation","Policy_Lever":"Hybrid-electric refrigerated urban vehicle adoption","Freight_Segment":"Cold-chain urban","Data_Source":"Real Vienna delivery cycles","Key_Finding":"Hybrid refrigerated delivers major energy efficiency gains","Stated_Limitations":"Single vehicle concept","ML_AI_Gap":"RL energy-management strategy; predictive ML for cooling-load","Geography_Bucket":"Europe (EU)"},
# 78
{"Country":"Belgium","City":"Generic","Simulation_Type":"Optimization-based simulation","Software":"Not stated","Modeling_Method":"Two-tiered optimization with instance generator","Policy_Lever":"Reserved lanes / two-tier city-logistics","Freight_Segment":"Urban + metro distribution","Data_Source":"Instance generator","Key_Finding":"Methodology + instance generator proposed","Stated_Limitations":"Single instance tested","ML_AI_Gap":"Learning-to-optimize for two-tier solvers; transfer across cities","Geography_Bucket":"Europe (EU)"},
# 79
{"Country":"Italy","City":"Multiple Italian cities","Simulation_Type":"DSS + simulation","Software":"CLASS","Modeling_Method":"DSS integrating aggregate simulation of freight systems","Policy_Lever":"City logistics measure + scenario analysis","Freight_Segment":"Urban freight","Data_Source":"Italian urban data","Key_Finding":"DSS supports level-of-service analysis for decision-makers","Stated_Limitations":"Aggregate modeling","ML_AI_Gap":"ML-augmented DSS with what-if forecasts; dashboards driven by streaming data","Geography_Bucket":"Europe (EU)"},
# 80
{"Country":"Italy","City":"Not specified (Italian)","Simulation_Type":"Discrete-event microsimulation","Software":"Not stated","Modeling_Method":"DES of freight interchange warehouse","Policy_Lever":"Freight UDC warehouse design","Freight_Segment":"Urban distribution center","Data_Source":"Warehouse process data","Key_Finding":"Micro-sim supports ex-ante + ex-post design decisions","Stated_Limitations":"Warehouse-specific","ML_AI_Gap":"Digital-twin ML for real-time warehouse throughput optimization","Geography_Bucket":"Europe (EU)"},
# 81
{"Country":"Canada","City":"Edmonton","Simulation_Type":"Tour-based microsimulation","Software":"Custom CVM","Modeling_Method":"Iterative parameter adjustment to roadside survey","Policy_Lever":"Commercial vehicle model update methodology","Freight_Segment":"Urban commercial vehicle","Data_Source":"2012 Edmonton Roadside Commercial Vehicle Survey","Key_Finding":"Iterative adjustment reproduces count data without full re-estimation","Stated_Limitations":"Limited to parameter tweaks","ML_AI_Gap":"Bayesian online updating of CVM; ML demand imputation from passive data","Geography_Bucket":"North America (Canada)"},
# 82
{"Country":"Canada","City":"Toronto CBD","Simulation_Type":"Delivery simulation","Software":"Not stated","Modeling_Method":"Demand simulation + consolidation-center routing","Policy_Lever":"Urban freight consolidation center","Freight_Segment":"Courier + small package","Data_Source":"Toronto CBD demand","Key_Finding":"Savings grow with more participating companies; less with more deliveries","Stated_Limitations":"Scenario-based","ML_AI_Gap":"ML participation-prediction for UCC market share; RL consolidation-routing","Geography_Bucket":"North America (Canada)"},
# 83
{"Country":"Australia","City":"Not specified (methodology)","Simulation_Type":"Traffic microsimulation + evolutionary optimization","Software":"Unspecified microsim + parallel PSO","Modeling_Method":"Parallel PSO (32 CPUs) for microsim auto-calibration","Policy_Lever":"Calibration methodology enabling heterogeneous-traffic analysis","Freight_Segment":"Mixed heavy + passenger","Data_Source":"Calibration dataset","Key_Finding":"25× runtime reduction vs unparalleled EA","Stated_Limitations":"PSO local-minima risk","ML_AI_Gap":"Bayesian optimization / deep-learning surrogate calibration instead of PSO","Geography_Bucket":"Oceania"},
# 84
{"Country":"USA","City":"Alameda Corridor, Los Angeles","Simulation_Type":"Microscopic traffic simulation + emissions","Software":"TransModeler + MOVES","Modeling_Method":"24-hr sim of freeways + arterials","Policy_Lever":"Off-peak drayage shifting (PierPASS)","Freight_Segment":"Port drayage","Data_Source":"LA/Long Beach port data","Key_Finding":"Small net emission drops; peak −10%, off-peak +28%","Stated_Limitations":"Health impacts need separate analysis","ML_AI_Gap":"ML-based off-peak cost-elasticity modeling; CV drayage-flow counting","Geography_Bucket":"USA"},
# 85
{"Country":"Spain","City":"Not specified (Spanish)","Simulation_Type":"Microsimulation","Software":"Not stated","Modeling_Method":"Abstract truncated","Policy_Lever":"Pedestrianisation impact on urban freight deliveries","Freight_Segment":"Urban delivery","Data_Source":"Abstract truncated","Key_Finding":"Abstract not available","Stated_Limitations":"Abstract missing","ML_AI_Gap":"ML curb-space re-allocation under pedestrianisation; pedestrian-vehicle interaction ML","Geography_Bucket":"Europe (EU)"},
# 86
{"Country":"Italy","City":"Reggio Calabria","Simulation_Type":"Aggregate freight demand simulation","Software":"Not stated","Modeling_Method":"Aggregate UDC impact models","Policy_Lever":"Urban Distribution Center","Freight_Segment":"Urban distribution","Data_Source":"Reggio Calabria data","Key_Finding":"UDC can be competitive and balance carrier transhipment cost","Stated_Limitations":"Aggregate","ML_AI_Gap":"ML UDC pricing optimization; demand-elasticity ML","Geography_Bucket":"Europe (EU)"},
# 87
{"Country":"USA","City":"Chicago","Simulation_Type":"Dynamic network traffic simulation-assignment (DTA)","Software":"Custom DTA","Modeling_Method":"Time-dependent shortest path + k-opt TDVRP heuristic","Policy_Lever":"Time-dependent freight routing under congestion","Freight_Segment":"Urban long-haul","Data_Source":"Chicago network","Key_Finding":"TDVRP solvable at 500-customer scale on real network","Stated_Limitations":"Heuristic","ML_AI_Gap":"Neural solver for TDVRP; spatio-temporal GNN travel-time prediction","Geography_Bucket":"USA"},
# 88
{"Country":"Italy","City":"Calabria (Kuehne+Nagel platform)","Simulation_Type":"Discrete-event microsimulation","Software":"Witness","Modeling_Method":"Stochastic DES platform ops","Policy_Lever":"Logistic platform operations","Freight_Segment":"Interregional platform","Data_Source":"Kuehne+Nagel data","Key_Finding":"DES useful for tactical/strategic platform planning","Stated_Limitations":"Single platform","ML_AI_Gap":"Digital-twin ML live integration; RL platform dispatching","Geography_Bucket":"Europe (EU)"},
# 89
{"Country":"USA","City":"Alameda Corridor, LA","Simulation_Type":"Microscopic traffic + emission + dispersion + health","Software":"Not stated (4-model chain)","Modeling_Method":"Coupled traffic-emission-dispersion-health model","Policy_Lever":"Clean Truck Program (CTP)","Freight_Segment":"Drayage","Data_Source":"LA/LB port, 2005-2012","Key_Finding":"Drayage PM health costs dropped 36→96% post-CTP","Stated_Limitations":"Model-chain propagation error","ML_AI_Gap":"End-to-end ML health-impact surrogate; causal ML for CTP attribution","Geography_Bucket":"USA"},
# 90
{"Country":"USA","City":"Generic urban corridor","Simulation_Type":"Microsimulation + statistical + optimization","Software":"Not stated","Modeling_Method":"Externality cost functions + optimization","Policy_Lever":"Truck-type mix for urban deliveries","Freight_Segment":"Urban trucks","Data_Source":"Real corridor","Key_Finding":"Optimal when single-unit truckload ≤2/3 of heavy-truck load","Stated_Limitations":"Single corridor","ML_AI_Gap":"ML externality cost estimation from sensor data","Geography_Bucket":"USA"},
# 91
{"Country":"USA","City":"Generic urban corridor","Simulation_Type":"Microsimulation + optimization","Software":"Not stated","Modeling_Method":"Externality cost functions (updated version of #90)","Policy_Lever":"Truck-type mix","Freight_Segment":"Urban trucks","Data_Source":"Real corridor","Key_Finding":"Same as #90","Stated_Limitations":"Duplicate of #90","ML_AI_Gap":"Same as #90","Geography_Bucket":"USA"},
# 92
{"Country":"Australia","City":"Not specified","Simulation_Type":"Freight network simulation","Software":"Not stated","Modeling_Method":"Case-study simulations across commodities","Policy_Lever":"Performance-Based Standards (PBS) heavy vehicles","Freight_Segment":"Urban freight heavy vehicles","Data_Source":"Australian case studies","Key_Finding":"PBS vehicles lower kms/trips/times in urban freight","Stated_Limitations":"Case-study scope","ML_AI_Gap":"ML access-network feasibility analysis for PBS vehicles","Geography_Bucket":"Oceania"},
# 93
{"Country":"Canada","City":"Hamilton, Ontario","Simulation_Type":"Integrated urban modeling + scenario simulation","Software":"Not stated","Modeling_Method":"Multi-regional economic + urban modeling","Policy_Lever":"Gateway city sustainable development","Freight_Segment":"Gateway-city freight","Data_Source":"Hamilton data","Key_Finding":"Gateway development + LRT + compact form = sustainable","Stated_Limitations":"Transferability conditional on calibration","ML_AI_Gap":"Transfer-learning for gateway-city ML models","Geography_Bucket":"North America (Canada)"},
# 94
{"Country":"Germany","City":"Not specified (methodology)","Simulation_Type":"Multi-agent transport simulation","Software":"MATSim (jsprit)","Modeling_Method":"3-tier agents: shippers/TSPs/carriers integrated with passenger traffic","Policy_Lever":"Multi-agent freight framework","Freight_Segment":"Urban + passenger coupled","Data_Source":"Fictitious scenario","Key_Finding":"Framework enables policy-measure simulation across tiers","Stated_Limitations":"Proof-of-concept","ML_AI_Gap":"Hierarchical RL across 3 tiers; ML calibration of each tier","Geography_Bucket":"Europe (EU)"},
# 95
{"Country":"Italy","City":"Generic Italian road network","Simulation_Type":"Simulation method for cost evaluation","Software":"Not stated","Modeling_Method":"Trip-planning tool + demand generator","Policy_Lever":"Delivery time windows","Freight_Segment":"Urban freight distribution","Data_Source":"Synthetic scenarios","Key_Finding":"Indicators predict transportation costs under TW profiles","Stated_Limitations":"Synthetic scenarios","ML_AI_Gap":"ML demand generator calibrated to real cities","Geography_Bucket":"Europe (EU)"},
# 96
{"Country":"Italy","City":"Civitavecchia (port)","Simulation_Type":"Discrete-event microsimulation","Software":"Not stated","Modeling_Method":"DES of port vessel + truck + equipment interactions","Policy_Lever":"Port berth allocation + navigation priorities","Freight_Segment":"Seaport operations","Data_Source":"Port of Civitavecchia","Key_Finding":"Micro-sim supports DSS for port authority","Stated_Limitations":"Single port","ML_AI_Gap":"ML vessel-arrival prediction; RL berth allocation under stochastic arrivals","Geography_Bucket":"Europe (EU)"},
# 97
{"Country":"Italy","City":"Not specified","Simulation_Type":"Aggregate + disaggregate ex-ante assessment model","Software":"Not stated","Modeling_Method":"2-level model: commodity + vehicle","Policy_Lever":"City-logistics measures ex-ante assessment","Freight_Segment":"Urban freight","Data_Source":"Italian","Key_Finding":"Open-architecture framework for policy ex-ante evaluation","Stated_Limitations":"Aggregate","ML_AI_Gap":"ML end-consumer demand prediction; scenario-generation ML","Geography_Bucket":"Europe (EU)"},
# 98
{"Country":"Italy","City":"Not specified","Simulation_Type":"Multi-step modeling system","Software":"Not stated","Modeling_Method":"Disaggregate commodity + vehicle flows","Policy_Lever":"Urban freight policy DSS","Freight_Segment":"Urban freight","Data_Source":"Italian","Key_Finding":"Model system links consumer and restocking choices","Stated_Limitations":"Aggregate architecture","ML_AI_Gap":"Neural demand generation from POS data","Geography_Bucket":"Europe (EU)"},
# 99
{"Country":"Japan","City":"N/A (review)","Simulation_Type":"Review of risk simulation methods","Software":"N/A","Modeling_Method":"Review (stochastic, multi-objective, robust, MAS, traffic sim)","Policy_Lever":"Risk incorporation in city logistics","Freight_Segment":"Urban freight under risk","Data_Source":"Literature","Key_Finding":"Human-security engineering important for risk-aware policy","Stated_Limitations":"Review","ML_AI_Gap":"ML-based risk forecasting; distributional RL for risk-sensitive policy","Geography_Bucket":"Asia"},
# 100
{"Country":"USA","City":"Not specified (84-node test)","Simulation_Type":"Hybrid microsimulation","Software":"Not stated","Modeling_Method":"Discrete-choice tour generation + trip-chaining","Policy_Lever":"Trip-chaining behavior modeling","Freight_Segment":"Urban freight","Data_Source":"Integrative freight market simulation","Key_Finding":"Distance, cargo amount, return distance drive tour decisions","Stated_Limitations":"Test network, not real","ML_AI_Gap":"Sequence models (RNN/Transformer) for tour-chain prediction","Geography_Bucket":"USA"},
# 101
{"Country":"Italy","City":"Not specified","Simulation_Type":"Fixed-point + network assignment simulation","Software":"Not stated","Modeling_Method":"Multimodal fixed-point assignment with crossed congestion","Policy_Lever":"Multimodal urban freight assignment","Freight_Segment":"Urban trucks + cars + buses","Data_Source":"Real-dimension network","Key_Finding":"Neglecting multimodal aspects changes freight min-cost paths","Stated_Limitations":"Fixed-point convergence","ML_AI_Gap":"GNN traffic assignment; ML-accelerated fixed-point solvers","Geography_Bucket":"Europe (EU)"},
# 102
{"Country":"USA","City":"Denver region","Simulation_Type":"Aggregate tour-based entropy maximization","Software":"PDCO solver","Modeling_Method":"Entropy max for tour generation","Policy_Lever":"Aggregate freight demand forecasting","Freight_Segment":"Urban commercial vehicle","Data_Source":"Denver region tour observations","Key_Finding":"MAPE ~6.6-6.7% between estimated and observed tours","Stated_Limitations":"Aggregate approach","ML_AI_Gap":"Neural entropy-regularized tour generation; transformer for tour synthesis","Geography_Bucket":"USA"},
# 103
{"Country":"Norway + Sweden","City":"National","Simulation_Type":"Micro-simulation of firm-to-firm logistics","Software":"Custom","Modeling_Method":"Firm-to-firm logistic choice model with deterministic cost minimization","Policy_Lever":"Shipment size + transport chain","Freight_Segment":"National freight (inter-firm)","Data_Source":"Norway + Sweden national data","Key_Finding":"Logistics model feasible at firm-to-firm scale","Stated_Limitations":"Deterministic cost; disaggregate data gap","ML_AI_Gap":"ML firm-behavior classification; neural choice models with stochastic utilities","Geography_Bucket":"Europe (other)"},
# 104
{"Country":"Australia","City":"Brisbane","Simulation_Type":"Microsimulation","Software":"Custom (first-principles)","Modeling_Method":"Stochastic vehicle-characteristic microsim","Policy_Lever":"Corridor-level freight policy (speed limits, signal settings, lane restrictions)","Freight_Segment":"Urban arterial freight","Data_Source":"Brisbane chase-car GPS data","Key_Finding":"Corridor performance sensitive to control measures; some policies improve efficiency","Stated_Limitations":"Single corridor","ML_AI_Gap":"ML-based adaptive signal timing with truck-awareness; CV truck-classification","Geography_Bucket":"Oceania"},
# 105
{"Country":"Norway + Sweden","City":"National","Simulation_Type":"Micro-simulation (logistics model)","Software":"Custom","Modeling_Method":"Micro-sim of logistics decisions with aggregate calibration","Policy_Lever":"National freight forecasting","Freight_Segment":"National commodity flows","Data_Source":"Norway + Sweden commodity flows","Key_Finding":"Micro-sim calibrated against aggregate data feasible","Stated_Limitations":"Aggregate calibration","ML_AI_Gap":"Disaggregate ML models combining multiple data sources","Geography_Bucket":"Europe (other)"},
# 106
{"Country":"Japan","City":"Tokyo Metropolitan Area","Simulation_Type":"Microsimulation","Software":"Custom","Modeling_Method":"Four-step modification with individual agent behavior","Policy_Lever":"Urban freight agent modeling","Freight_Segment":"Urban commodity + trucks","Data_Source":"Tokyo data","Key_Finding":"Agent-interaction microsim validated against observed truck flows","Stated_Limitations":"Three of four steps only","ML_AI_Gap":"End-to-end neural freight-demand model","Geography_Bucket":"Asia"},
# 107
{"Country":"Japan","City":"Not specified (methodology)","Simulation_Type":"VRPTW simulation","Software":"Not stated","Modeling_Method":"VRPTW + route/schedule optimization","Policy_Lever":"Cooperative freight + access restriction + road pricing","Freight_Segment":"City logistics","Data_Source":"Hypothetical","Key_Finding":"Cooperative systems + road pricing together most effective","Stated_Limitations":"Hypothetical","ML_AI_Gap":"RL for joint pricing + cooperation design; neural VRP solvers","Geography_Bucket":"Asia"},
# 108
{"Country":"Japan","City":"Test road network","Simulation_Type":"Stakeholder-interaction simulation","Software":"Not stated","Modeling_Method":"5-stakeholder behavioral simulation","Policy_Lever":"Urban expressway tolling","Freight_Segment":"Urban expressway freight","Data_Source":"Test network","Key_Finding":"Half-price tolls favorable for multiple stakeholders","Stated_Limitations":"Test network","ML_AI_Gap":"Mechanism design via RL across stakeholders","Geography_Bucket":"Asia"},
# 109
{"Country":"USA","City":"Alabama (statewide)","Simulation_Type":"Discrete-event simulation","Software":"ATIM","Modeling_Method":"Statewide DES","Policy_Lever":"Non-urban freight forecasting","Freight_Segment":"Non-urban / rural freight","Data_Source":"Alabama statewide","Key_Finding":"ATIM identifies non-MPO congestion","Stated_Limitations":"Statewide aggregate","ML_AI_Gap":"ML non-urban demand from census/industry data","Geography_Bucket":"USA"},
# 110
{"Country":"Belgium","City":"Belgian cities","Simulation_Type":"Urban freight simulation","Software":"INFACT","Modeling_Method":"Generalized-cost model with Intercept-and-Follow household survey","Policy_Lever":"Urban freight policy for logistics + household purchase","Freight_Segment":"Upstream + downstream urban","Data_Source":"Belgian urban data","Key_Finding":"Policy effects in opposite directions across transport streams","Stated_Limitations":"Pilot methodology","ML_AI_Gap":"Integrated ML of household purchase + supply response","Geography_Bucket":"Europe (EU)"},
# 111
{"Country":"Australia","City":"Brisbane (suburban)","Simulation_Type":"Microsimulation","Software":"Custom (first-principles)","Modeling_Method":"Stochastic vehicle-characteristic microsim (earlier version of #104)","Policy_Lever":"Corridor-level freight policy","Freight_Segment":"Urban arterial freight","Data_Source":"Brisbane chase-car","Key_Finding":"Corridor sensitive to control measures","Stated_Limitations":"Single corridor","ML_AI_Gap":"As #104","Geography_Bucket":"Oceania"},
# 112
{"Country":"Australia / USA","City":"N/A (review)","Simulation_Type":"Review / taxonomy","Software":"N/A","Modeling_Method":"Category review of freight model types","Policy_Lever":"Freight modeling directions","Freight_Segment":"Freight (general)","Data_Source":"Literature","Key_Finding":"4 categories of freight models; data + agent elements need attention","Stated_Limitations":"Review","ML_AI_Gap":"ML + ITS real-time data integration into freight models","Geography_Bucket":"Oceania"},
# 113
{"Country":"Japan","City":"Test road network","Simulation_Type":"VRPTW + traffic simulation","Software":"Not stated","Modeling_Method":"VRPTW + traffic simulation","Policy_Lever":"E-commerce (B2C) + cooperative delivery + time windows + pickup points","Freight_Segment":"Last-mile home delivery","Data_Source":"Test network","Key_Finding":"E-commerce may worsen traffic unless widely adopted; cooperative + TW + pickup reduce costs/emissions","Stated_Limitations":"Test network","ML_AI_Gap":"Demand-prediction ML for B2C volumes; RL pickup-point activation","Geography_Bucket":"Asia"},
# 114
{"Country":"Belgium","City":"Brussels","Simulation_Type":"Urban traffic assignment simulation","Software":"Not stated","Modeling_Method":"Two-user-class assignment + difference analysis","Policy_Lever":"Freight-transport policy reformulation","Freight_Segment":"Urban freight","Data_Source":"Brussels network","Key_Finding":"Lorry impacts quantified via differential assignment","Stated_Limitations":"Differential method","ML_AI_Gap":"Neural assignment for multi-class flows","Geography_Bucket":"Europe (EU)"},
# 115
{"Country":"Netherlands","City":"Not specified","Simulation_Type":"Simulation + GIS","Software":"GIS-based","Modeling_Method":"Simulation with GIS integration","Policy_Lever":"Urban freight policy / accessibility + environment","Freight_Segment":"Urban goods","Data_Source":"Dutch city","Key_Finding":"GIS-coupled simulation useful as DSS","Stated_Limitations":"1996 era","ML_AI_Gap":"Modern spatial ML (GeoAI) vastly extends this early GIS approach","Geography_Bucket":"Europe (EU)"},
# 116
{"Country":"Netherlands","City":"Not specified","Simulation_Type":"Simulation + GIS","Software":"GIS-based","Modeling_Method":"Accessibility + environment modeling","Policy_Lever":"Accessibility measurement for urban goods","Freight_Segment":"Urban goods","Data_Source":"Dutch city","Key_Finding":"Accessibility indicators defined and simulated","Stated_Limitations":"1994 era","ML_AI_Gap":"GeoAI accessibility metrics; graph-based accessibility ML","Geography_Bucket":"Europe (EU)"},
# 117
{"Country":"USA","City":"Florida (project)","Simulation_Type":"Microsimulation + UE assignment","Software":"Not stated","Modeling_Method":"Multiclass UE with flow-dependent PCE; HCM-based travel time","Policy_Lever":"Network-level truck analysis with travel-time reliability","Freight_Segment":"Network-wide truck","Data_Source":"N/A (research project)","Key_Finding":"Method advances flow-dependent PCE assignment","Stated_Limitations":"Reliability compute burden (hundreds of runs)","ML_AI_Gap":"Neural surrogate for reliability analysis to cut compute; ML-based PCE prediction from flow","Geography_Bucket":"USA"},
# 118
{"Country":"USA","City":"Chicago (UIC)","Simulation_Type":"Behavioral microsimulation","Software":"FAME","Modeling_Method":"Behavioral freight movement microsim linked to network sim","Policy_Lever":"Sustainable freight policies (curfew, load/time restrictions)","Freight_Segment":"Urban freight","Data_Source":"Chicago/UIC prior work","Key_Finding":"FAME + network sim enables policy test-bed","Stated_Limitations":"Project, not paper","ML_AI_Gap":"RL policy-search over FAME for best-performing policy bundles","Geography_Bucket":"USA"},
]

assert len(EXTRACTIONS) == 119, f"Expected 119, got {len(EXTRACTIONS)}"
